name: Tests

on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel

jobs:

  tests:
    name: Test code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.14.x
          - 1.16.x
          - 1.17.x
          - 1.18.x
          - 1.19.x
          - 1.x
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 200

    - name: Test
      run: |
        go test

